<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <AssemblyName>Microsoft.EntityFrameworkCore.AzureTable.FunctionalTests</AssemblyName>
    <RootNamespace>Microsoft.EntityFrameworkCore.AzureTable</RootNamespace>
    <ImplicitUsings>true</ImplicitUsings>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <!-- Avoid referencing EFCore.Relational -->
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.Diagnostics" />
    <Using Include="Microsoft.EntityFrameworkCore" />
    <Using Include="Microsoft.EntityFrameworkCore.Infrastructure" />
    <Using Include="Microsoft.EntityFrameworkCore.Metadata" />
    <Using Include="Microsoft.EntityFrameworkCore.Storage" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EFCore.AzureTable\EFCore.AzureTable.csproj" />
    <ProjectReference Include="..\..\src\EFCore\EFCore.csproj" />
    <ProjectReference Include="..\EFCore.Specification.Tests\EFCore.Specification.Tests.csproj" />
  </ItemGroup>

</Project>