// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure;
using Microsoft.EntityFrameworkCore.ValueGeneration;

namespace Microsoft.EntityFrameworkCore.AzureTable.Metadata.Conventions.Internal;

/// <summary>
///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
///     the same compatibility standards as public APIs. It may be changed or removed without notice in
///     any release. You should only use it directly in your code with extreme caution and knowing that
///     doing so can result in application failures when updating to a new Entity Framework Core release.
/// </summary>
public class AzureTableValueGenerationConvention : ValueGenerationConvention
{
    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    public AzureTableValueGenerationConvention(
        ProviderConventionSetBuilderDependencies dependencies)
        : base(dependencies)
    {
    }


    /// <inheritdoc />
    protected override ValueGenerated? GetValueGenerated(IConventionProperty property)
    {
        // ETag and Timestamp are always generated by Azure Table Storage
        if (property.FindAnnotation(AzureTableAnnotationNames.ETag) != null ||
            property.FindAnnotation(AzureTableAnnotationNames.Timestamp) != null)
        {
            return ValueGenerated.OnAddOrUpdate;
        }

        // For key properties that are GUIDs, we can generate values
        var declaringEntityType = property.DeclaringType as IReadOnlyEntityType;
        if (declaringEntityType != null && property.ClrType == typeof(Guid))
        {
            var partitionKeyProperty = declaringEntityType.GetPartitionKeyProperty();
            var rowKeyProperty = declaringEntityType.GetRowKeyProperty();
            
            if (property == partitionKeyProperty || property == rowKeyProperty)
            {
                return ValueGenerated.OnAdd;
            }
        }

        return base.GetValueGenerated(property);
    }
}