<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Azure Table Storage provider for Entity Framework Core.</Description>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <MinClientVersion>3.6</MinClientVersion>
    <AssemblyName>Microsoft.EntityFrameworkCore.AzureTable</AssemblyName>
    <RootNamespace>Microsoft.EntityFrameworkCore.AzureTable</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PackageTags>$(PackageTags);Azure Table Storage;NoSQL</PackageTags>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.Diagnostics" />
    <Using Include="System.Linq.Expressions" />
    <Using Include="System.Reflection" />
    <Using Include="Azure.Data.Tables" />
    <Using Include="Microsoft.EntityFrameworkCore" />
    <Using Include="Microsoft.EntityFrameworkCore.ChangeTracking" />
    <Using Include="Microsoft.EntityFrameworkCore.Diagnostics" />
    <Using Include="Microsoft.EntityFrameworkCore.Design" />
    <Using Include="Microsoft.EntityFrameworkCore.Infrastructure" />
    <Using Include="Microsoft.EntityFrameworkCore.Metadata" />
    <Using Include="Microsoft.EntityFrameworkCore.Metadata.Builders" />
    <Using Include="Microsoft.EntityFrameworkCore.Metadata.Conventions" />
    <Using Include="Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure" />
    <Using Include="Microsoft.EntityFrameworkCore.Query" />
    <Using Include="Microsoft.EntityFrameworkCore.Storage" />
    <Using Include="Microsoft.EntityFrameworkCore.Storage.ValueConversion" />
    <Using Include="Microsoft.EntityFrameworkCore.Update" />
    <Using Include="Microsoft.EntityFrameworkCore.ValueGeneration" />
    <Using Include="Microsoft.EntityFrameworkCore.Utilities" />
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCore\EFCore.csproj" />
    <ProjectReference Include="..\EFCore.Analyzers\EFCore.Analyzers.csproj" ReferenceOutputAssembly="False" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\AzureTableStrings.Designer.cs">
      <DependentUpon>AzureTableStrings.Designer.tt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\AzureTableStrings.Designer.tt">
      <CustomToolNamespace>Microsoft.EntityFrameworkCore.AzureTable.Internal</CustomToolNamespace>
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>AzureTableStrings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>